// Code generated by "stringer -type=Type -linecomment"; DO NOT EDIT.

package openapi

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TypeString-0]
	_ = x[TypeInteger-1]
	_ = x[TypeNumber-2]
	_ = x[TypeBoolean-3]
	_ = x[TypeArray-4]
	_ = x[TypeObject-5]
}

const _Type_name = "stringintegernumberbooleanarrayobject"

var _Type_index = [...]uint8{0, 6, 13, 19, 26, 31, 37}

func (i Type) String() string {
	if i < 0 || i >= Type(len(_Type_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
